/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Limit TODO/FIXME tags amount in file
 */
export interface MaxTagsOptions {
  /**
   * Scope: Project
   */
  project?: {
    /**
     * Max allowed TOOD/FIXME tags
     */
    max?: number;
    /**
     * Is scope disabled
     */
    disabled?: boolean;
  };
  /**
   * Scope: File
   */
  file?: {
    /**
     * Max allowed TOOD/FIXME tags
     */
    max?: number;
    /**
     * Is scope disabled
     */
    disabled?: boolean;
  };
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate relevanting of line's comment doclet
 */
export interface RelevantCommentsOptions {
  /**
   * Scope: Line
   */
  line?: {
    /**
     * Specify base validating entity
     */
    by?: "commit" | "days";
    /**
     * Allowable diff between commits/days (for validating)
     */
    diff?: number;
    /**
     * Is scope disabled
     */
    disabled?: boolean;
  };
  /**
   * Scope: Block
   */
  block?: {
    /**
     * Specify base validating entity
     */
    by?: "commit" | "days";
    /**
     * Allowable diff between commits/days (for validating)
     */
    diff?: number;
    /**
     * Is scope disabled
     */
    disabled?: boolean;
  };
  /**
   * Scope: Module
   */
  module?: {
    /**
     * Specify base validating entity
     */
    by?: "commit" | "days";
    /**
     * Allowable diff between commits/days (for validating)
     */
    diff?: number;
    /**
     * Is scope disabled
     */
    disabled?: boolean;
  };
}
